disabled_rules:
  - file_length
  - function_body_length
  - line_length
  - nesting
  - shorthand_operator
  - trailing_whitespace
  - type_body_length
  - vertical_whitespace
  - void_return

excluded:
  - Pods
  - Carthage

variable_name:
  excluded:
    - id
    - ok
    - vc
    - x
    - y
